### ISSUE TITLE
Adding AutoShape...

### ISSUE THREAD

**Issue by MastaDan9** [Himly1/roadhog-cheat#1]
Hi, I got hung up on Adding AutoShape..., waited 30 minutes, nothing happened...

```
`YOLOv5  2022-10-17 Python-3.9.13 torch-1.12.1+cpu CPU

Fusing layers... 
Model summary: 290 layers, 20852934 parameters, 0 gradients, 47.9 GFLOPs
Adding AutoShape... `
```

**Comment by Himly1** [comment]
@MastaDan9  Sorry for my late reply. 
Thats mean its working!!! you dont have to worry anything.
